import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Héctor Lara",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Tirzo Tarzo Turzo",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Sony EX14AP",
      slug: "sony-ex14ap",
      category: "Audifonos",
      image: "https://m.media-amazon.com/images/I/416636oHkoL._AC_SX355_.jpg",
      price: 169,
      brand: "Sony",
      rating: 2.4,
      numReviews: 12,
      countInStock: 122,
      description:
        "Auriculares intrauditivos Llevan música de Calidad cómodamente a Tus oídos, Gracias a su Rendimiento de Graves Mejorado, Controladores de Altavoz de 14,2 mm para Unos Graves Profundos",
    },
    {
      name: "Samsung Galaxy S10e G970U",
      slug: "samsunggalaxys10eg970u",
      category: "Celulares",
      image: "https://m.media-amazon.com/images/I/61iqeiEemFL._AC_SY606_.jpg",
      price: 4678,
      brand: "Samsung ",
      rating: 3.7,
      numReviews: 9,
      countInStock: 18,
      description:
        "128 GB de almacenamiento, Modelo Cardenal Rojo para Verizon",
    },
    {
      name: "Samsung Galaxy S10e",
      slug: "samsunggalaxys10e",
      category: "Celulares",
      image: "https://m.media-amazon.com/images/I/716g8PSrDaL._AC_SY355_.jpg",
      price: 3596,
      brand: "Samsung ",
      rating: 3.7,
      numReviews: 9,
      countInStock: 18,
      description: "128 GB de almacenamiento, Modelo Prism Black",
    },
    {
      name: "Legion 5 17.3",
      slug: "Legion-5",
      category: "Laptops",
      image: "https://m.media-amazon.com/images/I/61f8ugUYqsL._AC_SY355_.jpg",
      price: 17072,
      brand: "Lenovo",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        "Lenovo Legion 5 Computadora portátil para juegos, pantalla FHD IPS de 15.6 pulgadas, AMD Ryzen 5 4600H, cámara web, teclado retroiluminado, Wi-Fi 6, USB-C, HDMI, GeForce GTX 1650 Ti, Windows 10 Home, memoria de 8 GB, SSD PCIe de 256 GB + disco duro de 1 TB",
    },
  ],
};

export default data;

// const data = {
//   users: [
//     {
//       name: "admin",
//       email: "admin@admin.com",
//       password: bcrypt.hashSync("admin1"),
//       isAdmin: true,
//     },
//     {
//       name: "Luis",
//       email: "luis@colochosama.com",
//       password: bcrypt.hashSync("123456"),
//       isAdmin: false,
//     },
//   ],
//   products: [
//     {
//       name: "Free Shirt",
//       slug: "free-shirt",
//       category: "Shirts",
//       image: "/images/shirt1.jpg",
//       price: 70,
//       brand: "Nike",
//       rating: 4.5,
//       numReviews: 8,
//       countInStock: 20,
//       description: "A popular shirt",
//     },
//     {
//       name: "Fit Shirt",
//       slug: "fit-shirt",
//       category: "Shirts",
//       image: "/images/shirt2.jpg",
//       price: 80,
//       brand: "Adidas",
//       rating: 3.2,
//       numReviews: 10,
//       countInStock: 20,
//       description: "A popular shirt",
//     },
//     {
//       name: "Slim Shirt",
//       slug: "slim-shirt",
//       category: "Shirts",
//       image: "/images/shirt3.jpg",
//       price: 90,
//       brand: "Raymond",
//       rating: 4.5,
//       numReviews: 3,
//       countInStock: 20,
//       description: "A popular shirt",
//     },
//     {
//       name: "Golf Pants",
//       slug: "golf-pants",
//       category: "Pants",
//       image: "/images/pants1.jpg",
//       price: 90,
//       brand: "Oliver",
//       rating: 2.9,
//       numReviews: 13,
//       countInStock: 20,
//       description: "Smart looking pants",
//     },
//     {
//       name: "Fit Pants",
//       slug: "fit-pants",
//       category: "Pants",
//       image: "/images/pants2.jpg",
//       price: 95,
//       brand: "Zara",
//       rating: 3.5,
//       numReviews: 7,
//       countInStock: 20,
//       description: "A popular pants",
//     },
//     {
//       name: "Classic Pants",
//       slug: "classic-pants",
//       category: "Pants",
//       image: "/images/pants3.jpg",
//       price: 75,
//       brand: "Casely",
//       rating: 2.4,
//       numReviews: 14,
//       countInStock: 20,
//       description: "A popular pants",
//     },
//   ],
// };

// export default data;
